package com.nomealwaste.entity;
// Generated Jan 7, 2022, 5:56:42 AM by Hibernate Tools 5.5.7.Final

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private OrderDetailId id;
	private Meal meal;
	private MealOrder mealOrder;

	public OrderDetail() {
	}

	public OrderDetail(OrderDetailId id) {
		this.id = id;
	}

	public OrderDetail(OrderDetailId id, Meal meal, MealOrder mealOrder) {
		this.id = id;
		this.meal = meal;
		this.mealOrder = mealOrder;
	}

	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	public Meal getMeal() {
		return this.meal;
	}

	public void setMeal(Meal meal) {
		this.meal = meal;
	}

	public MealOrder getMealOrder() {
		return this.mealOrder;
	}

	public void setMealOrder(MealOrder mealOrder) {
		this.mealOrder = mealOrder;
	}

}
